---
title: "Module 11 - R Demo"
author: "DuraiSundaramoorthi"
output: pdf_document
---

## K-Means Clustering
## Code Chunk 1
```{r}
set.seed(2)

x = matrix(rnorm(50*2), ncol=2)

x[1:25,1] = x[1:25,1] + 3

x[1:25,2] = x[1:25,2] - 4

x
```

## Code Chunk 2
```{r}
km.out = kmeans(x,2,nstart=20)

km.out$cluster

plot(x, col=(km.out$cluster+1), main = "K-Means Clustering Results with K = 2", xlab="", ylab="", pch=20,cex=2)
```


## Code Chunk 3
```{r}
set.seed(4)

km.out=kmeans(x,3,nstart=20)

km.out

plot(x, col=(km.out$cluster+1), main = "K-Means Clustering Results with K = 3", xlab="", ylab="", pch=20,cex=2)
```


## Code Chunk 4
```{r}
set.seed(3)

km.out=kmeans(x,3,nstart=1)

km.out$tot.withinss

km.out=kmeans(x,3,nstart=20)

km.out$tot.withinss
```


## Hierarchical Clustering
## Code Chunk 5
```{r}
hc.complete = hclust(dist(x), method = "complete")

hc.average = hclust(dist(x), method = "average")

hc.single = hclust(dist(x), method = "single")

par(mfrow=c(1,3))

plot(hc.complete,main="Complete Linkage", xlab = "", sub="", cex=0.9)

plot(hc.average,main="Average Linkage", xlab = "", sub="", cex=0.9)

plot(hc.single,main="Single Linkage", xlab = "", sub="", cex=0.9)

par(mfrow=c(1,1))

```


## Code Chunk 6
```{r}
cutree(hc.complete,2)

cutree(hc.average,2)

cutree(hc.single,2)
```


## Code Chunk 7
```{r}
xsc = scale(x)

plot(hclust(dist(xsc),method = "complete"), main = "Hierarchical Clustering with Scaled Features")

```


## Code Chunk 8
```{r}
set.seed(2)

x = matrix(rnorm(30*3), ncol = 3)

transPdata = t(x)

Similarity = cor(transPdata)

Dissimilarity = 1-cor(Similarity)

DissimilarityDistance = as.dist(Dissimilarity)

plot(hclust(DissimilarityDistance,method = "complete"), main = "Complete Linkage with Correlation-Based Distance", xlab = "", sub="")
```

