---
title: "Module 7 R Demo"
author: "DuraiSundaramoorthi"
output: pdf_document
---

##Classification Tree
## Code Chunk 1

```{r}
library(ISLR)

attach(Carseats)

fix(Carseats)

High = ifelse(Sales<=8,"No","Yes")

High

Carseats=data.frame(Carseats,High)

names(Carseats)
```

## Code Chunk 2

```{r}
library(tree)

#Carseats$High = factor(Carseats$High)

tree.carseats = tree(High~.-Sales,Carseats)

summary(tree.carseats)

plot(tree.carseats)

text(tree.carseats,pretty=0)

tree.carseats
```


## Code Chunk 3

```{r}
set.seed(2)

train = sample(1:nrow(Carseats),200)

Carseats.test = Carseats[-train,]

High.test = High[-train]
```

## Code Chunk 4

```{r}
tree.carseats=tree(High~.-Sales,Carseats,subset=train)

tree.pred=predict(tree.carseats,Carseats.test,type="class")

table(tree.pred,High.test)

mean(tree.pred==High.test)
```

##Pruning
## Code Chunk 5

```{r}
set.seed(3)

cv.carseats=cv.tree(tree.carseats,FUN=prune.misclass)

names(cv.carseats)

cv.carseats
```

## Code Chunk 6

```{r}
par(mfrow=c(1,2))

plot(cv.carseats$size,cv.carseats$dev,type="b")

plot(cv.carseats$k,cv.carseats$dev,type="b")

par(mfrow=c(1,1))
```

## Code Chunk 7

```{r}
prune.carseats=prune.misclass(tree.carseats,best=9)

plot(prune.carseats)

text(prune.carseats,pretty=0)

tree.pred=predict(prune.carseats,Carseats.test,type="class")

table(tree.pred,High.test)

mean(tree.pred==High.test)
```

## Code Chunk 8

```{r}
prune.carseats=prune.misclass(tree.carseats,best=15)

plot(prune.carseats)

text(prune.carseats,pretty=0)

tree.pred=predict(prune.carseats,Carseats.test,type="class")

table(tree.pred,High.test)

mean(tree.pred==High.test)
```

## Regression Trees
## Code Chunk 9

```{r}
library(MASS)

set.seed(1)

train = sample(1:nrow(Boston),nrow(Boston)/2)
```

## Code Chunk 10

```{r}
tree.boston=tree(medv~.,Boston,subset=train)

summary(tree.boston)

plot(tree.boston)

text(tree.boston,pretty=0)
```

## Code Chunk 11

```{r}
yhat = predict(tree.boston,newdata=Boston[-train,]) 

boston.test=Boston[-train,"medv"]

mean((yhat-boston.test)^2)
```

##Pruning
## Code Chunk 12

```{r}
set.seed(1)

cv.boston=cv.tree(tree.boston)

plot(cv.boston$size,cv.boston$dev,type='b')

prune.boston=prune.tree(tree.boston,best=7)

plot(prune.boston)

text(prune.boston,pretty = 0)
```

